server:
  host: "localhost"
  port: "3001"
  mode: "release"

database:
  host: "localhost"
  port: 5432
  username: "keycloak"
  password: "password"
  name: "keycloak"
  scheme: "public"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
